spring.application.name=hello-openshift

# OpenShift attribue generalement le port via la variable PORT, mais 8080 est le standard
server.port=8080

# Endpoints actuator utiles pour les probes OpenShift (liveness/readiness)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
